apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: ingress-nginx-binding
  namespace: ingress-nginx
spec:
  ipAddressType: ipv6
  serviceRef:
    name: ingress-nginx-controller
    port: 443
  targetGroupARN: "arn:aws:elasticloadbalancing:us-west-2:014821610452:targetgroup/platform/4b7d67c9a7deb065"