FROM debian:trixie-slim AS build
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update > /dev/null \
    && apt-get install -y wget > /dev/null \
    && rm -rf /var/lib/apt/lists/*

FROM build as go
ARG VERSION=1.24.12
ARG TARGETARCH
ARG TARGETOS
WORKDIR /tmp
RUN wget -q -O tarball https://go.dev/dl/go${VERSION}.${TARGETOS}-${TARGETARCH}.tar.gz
RUN tar -xzf tarball

FROM build AS flyctl
ARG VERSION=0.3.145
ARG TARGETARCH
ARG TARGETOS
WORKDIR /tmp
RUN TARGETOS=$(if [ "${TARGETOS}" = "linux" ]; then echo "Linux"; fi) \
    && TARGETARCH=$(if [ "${TARGETARCH}" = "amd64" ]; then echo "x86_64"; fi) \
    && wget -q -O tarball https://github.com/superfly/flyctl/releases/download/v${VERSION}/flyctl_${VERSION}_${TARGETOS}_${TARGETARCH}.tar.gz
RUN tar -xzf tarball

FROM build AS kubectl
ARG VERSION=1.33.0
ARG TARGETARCH
ARG TARGETOS
WORKDIR /tmp
RUN wget -q https://dl.k8s.io/release/v${VERSION}/bin/${TARGETOS}/${TARGETARCH}/kubectl
RUN wget -q https://dl.k8s.io/release/v${VERSION}/bin/${TARGETOS}/${TARGETARCH}/kubectl.sha256
RUN echo "$(cat kubectl.sha256) kubectl" | sha256sum --check
RUN chmod 755 kubectl

FROM build AS helm
ARG VERSION=3.18.6
ARG TARGETARCH
ARG TARGETOS
WORKDIR /tmp
RUN wget -q -O tarball https://get.helm.sh/helm-v${VERSION}-${TARGETOS}-${TARGETARCH}.tar.gz
RUN tar -xzf tarball
RUN mv ${TARGETOS}-${TARGETARCH}/helm /tmp/helm

FROM ghcr.io/opentofu/opentofu:1.10-minimal AS tofu

FROM debian:trixie-slim AS final
ARG AWSCLI_VERSION=2.23.6
ARG TARGETARCH
ARG TARGETOS
COPY --from=flyctl /tmp/flyctl /usr/local/bin/fly
COPY --from=go /tmp/go/ /usr/local/go/
COPY --from=kubectl /tmp/kubectl /usr/local/bin/kubectl
COPY --from=helm /tmp/helm /usr/local/bin/helm
COPY --from=tofu /usr/local/bin/tofu /usr/local/bin/tofu
ENV PATH=${PATH}:/usr/local/go/bin
RUN apt-get update && apt-get install -y --no-install-recommends \
    ack \
    awscli=${AWSCLI_VERSION}-1 \
    ca-certificates \
    curl \
    dnsutils \
    git \
    gnupg \
    less \
    openssl \
    ssh \
    vim
RUN mkdir -p /etc/apt/keyrings
RUN curl -sLS https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | tee /etc/apt/keyrings/microsoft.gpg > /dev/null
RUN chmod go+r /etc/apt/keyrings/microsoft.gpg
RUN echo "Types: deb\nURIs: https://packages.microsoft.com/repos/azure-cli/\nSuites: bookworm\nComponents: main\nArchitectures: ${TARGETARCH}\nSigned-By: /etc/apt/keyrings/microsoft.gpg" | tee /etc/apt/sources.list.d/azure-cli.sources
RUN apt-get update && apt-get install -y --no-install-recommends \
    azure-cli
COPY .bashrc /root/.bashrc