apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-conf" .Release.Name }}
  labels: {{ include "labels" . | indent 4 }}
data:
  postgresql.conf: |
    {{- .Values.conf.postgresql | nindent 4 }}
  pg_hba.conf: |
    {{- .Values.conf.pg_hba | nindent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-sensitive" .Release.Name }}
  labels: {{ include "labels" . | indent 4 }}
data:
  {{- range $key, $value := .Values.secrets }}
    {{- printf "%s: %s" $key ($value | b64enc) | nindent 2 }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-tls" .Release.Name }}
  labels: {{ include "labels" . | indent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.crt | b64enc }}
  tls.key: {{ .Values.tls.key | b64enc }}