apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-headless" .Release.Name }}
  labels: {{ include "labels" . | indent 4 }}
spec:
  ports:
  - port: 5432
  clusterIP: None
  selector: {{ include "labels" . | indent 4 }}
