apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-data" .Release.Name }}
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 8Gi
